# Generated by Django 4.1.7 on 2023-03-18 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0002_product_user_money_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='last modify time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'withdraw log',
                'verbose_name_plural': 'withdraw logs',
            },
        ),
    ]
